[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
]

[profile.release]
lto = "thin"
debug = 0
incremental = false
panic = "abort"
codegen-units = 1
strip = true
opt-level = 3
